# Convergence variant (reduce_alpha)
system: zirconate
system: zirconate
voltage_V: 275.38
current_density_A_dm2: 8.5
time_min: 15.299999999999999
frequency_Hz: 750
duty_cycle_pct: 18.0
waveform: bipolar
